package com.search.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * SysUser generated by hbm2java
 */
@Entity
@Table(name = "SYS_USER")
public class SysUser implements java.io.Serializable,Cloneable {
	private static final long serialVersionUID = -2956985304828669724L;
	private String userid;
	private String userno;
	private String username;
	private String passwd;
	private String orgid;
	private String isvalid;
	private String note;
	private String orgname;

	
	public SysUser() {
	}

	public SysUser(String userid, String userno) {
		this.userid = userid;
		this.userno = userno;
	}

	public SysUser(String userid, String userno, String username,
			String passwd, String orgid, String isvalid, String note,String orgname) {
		this.userid = userid;
		this.userno = userno;
		this.username = username;
		this.passwd = passwd;
		this.orgid = orgid;
		this.isvalid = isvalid;
		this.note = note;
		this.orgname = orgname;
	}

	@Id
	@Column(name = "USERID", unique = true, nullable = false, length = 24)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "USERNO", nullable = false, length = 16)
	public String getUserno() {
		return this.userno;
	}

	public void setUserno(String userno) {
		this.userno = userno;
	}

	@Column(name = "USERNAME", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWD", length = 50)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "ORGID", length = 32)
	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	@Column(name = "ISVALID", length = 1)
	public String getIsvalid() {
		return this.isvalid;
	}

	public void setIsvalid(String isvalid) {
		this.isvalid = isvalid;
	}

	@Column(name = "NOTE", length = 1000)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Transient
	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	@Override 
    public Object clone() throws CloneNotSupportedException { 
        return super.clone(); 
    } 
}
